name: Update Documentation

on:
  push:
    paths:
      - 'docs/**'
    branches:
      - main  # Set a branch name to trigger deployment

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Pandoc and LaTeX
        run: |
          brew install pandoc pandoc-crossref

      - name: Build Documentation Site
        run: |
          make docs
          touch ./public/docs/.nojekyll

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public/docs/

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Deploy Documentation Website to AWS
        run: |
          aws s3 sync ./public/docs/* s3://lantern.northwestern.pub
